project: 
  type: website
  output-dir: docs 

execute:
  freeze: auto 

website:
  page-navigation: true  
  title: <br>"Hypersocks Team"
  site-url: "https://hypersocks.quarto.pub/hypersocks-team" 
  repo-url: https://hypersocks.quarto.pub/hypersocks-team
  repo-actions: [edit, source, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org)."
    left: "&copy; CC-By The Hypersocks Team (2024)."
 
  sidebar:
    title: "Hypersocks Team <br>"
    logo: images/logo.png
    pinned: true
    align: center
    tools: 
      - text: "Hypersocks Team website"
        icon: globe
        href: https://hypersocks.quarto.pub/hypersocks-team
      - text: "Hypersocks Team repo"
        icon: github
        href: https://github.com/lkampoli/hypersocks.team.io
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: index.qmd
      - text: "Team" 
        href: team/team.qmd 
      - text: "Research"
        href: research/index.qmd
      - text: "Codes"
        href: codes/index.qmd
      - text: "Publications"
        href: publications/index.qmd
      - text: "Grants"
        href: grants/index.md
      - text: "News"
        href: news/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    #mainfont: Nunito Sans
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true

filters:
  - include-files.lua
  - quarto
